### ISSUE TITLE
A starter template

### ISSUE THREAD

**Issue by thetarnav** [nativescript-community/solid-js#1]
Hey, we are planning on creating a guidepost website at the solid community on the [solid.new](https://solid.new) domain. It would contain a few selected links to places where you can start a different kinds of projects. (very much inspired by [astro.new](https://astro.new)) I think that creating a mobile app should be one of the categories, with this project as one of the options there.
So, would there be a possibility of creating, and maintaining a starter template that one can easily clone, degit, open in stackblitz, etc.?
Here are a couple of examples of existing solid templates that we want to use:
- https://github.com/solidjs/templates
- https://github.com/solidjs/solid-start/tree/main/examples
- https://github.com/olgam4/bat
- https://github.com/ionic-team/capacitor-solidjs-templates
- https://github.com/OrJDev/create-jd-app

**Comment by ClassicOldSong** [comment]
I think that playground link should be enough for a starter project

**Comment by ClassicOldSong** [comment]
https://stackblitz.com/edit/nativescript-dominative-solid?file=app/app.jsx

In case you missed it

**Comment by thetarnav** [comment]
hmm, yeah it could work for now
Making it into a template repository from that example shouldn't be hard as well. It would allow to open it in other tools quickly. But I'm fine with just the stackblitz link, it should be easy enough for people to start from.
Not sure if the lack of ts would scare some people off though 🤔

**Comment by ClassicOldSong** [comment]
Where would you like the repo to be hosted 🤔

I can create one if you need

**Comment by thetarnav** [comment]
anywhere is fine
A separate repository template is nice because you can easily use it from github
But any location works for degit/stackblitz/codesandbox thing
For example, you could have a `/example` dir in this repo and you could use it with
```
npx degit SudoMaker/dominative-solid/tree/main/example my-project
```

**Comment by ClassicOldSong** [comment]
https://github.com/ClassicOldSong/dominative-solid-template
Here's the template repo

**Comment by thetarnav** [comment]
This is perfect, thank you!
I'll let you know when the solid.new site gets deployed
